export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_UI_ROOT_EXPANDED = 'UPDATE_UI_ROOT_EXPANDED';
export const UPDATE_UI_SETTINGS_EXPANDED = 'UPDATE_UI_SETTINGS_EXPANDED';
export const UPDATE_UI_RESULTS_EXPANDED = 'UPDATE_UI_RESULTS_EXPANDED';
export const UPDATE_DOM_OBSERVER = 'UPDATE_DOM_OBSERVER';
export const ADD_NEW_RESULTS = 'ADD_NEW_RESULTS';
